Attempt to fix cosign...
error: "getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key"

sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
- this is actually v3.3.0 it seems, not v2.6.0
- also uses default cosign-release: 'v1.11.1', but 'v1.11.0' was fine too

need at least cosign-release: 'v1.13.0' to avoid docker failure
- see https://github.com/ossf/scorecard-action/issues/997
- main branch uses cosign-release: 'v1.13.1' as of v2.8.1